2022-06-11 16:37:32,934 DEBUG decos.py Была вызвана функция config_load с параметрами (), {}. Вызов из модуля __main__. Вызов из функции main().
2022-06-11 16:37:32,936 DEBUG decos.py Была вызвана функция arg_parser с параметрами ('', '7777'), {}. Вызов из модуля __main__. Вызов из функции main().
2022-06-11 16:37:32,975 INFO core.py Запущен сервер, порт для подключений: 7777, адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2022-06-11 16:37:54,162 INFO core.py Установлено соедение с ПК ('127.0.0.1', 51560)
2022-06-11 16:37:54,663 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1654954674.1801634, 'user': {'account_name': '111', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA5Z10UFQoI5/TSIXmt1LX\nGlEh46bKXtDVmjn3fO5C8RFO1heccW9sbAZRJbXwc1DVcpAX9appy4BLqWMSUYF7\nao2i9QNI4WFe7Mi+qshxoEKOfseyDd79hYZSRlZn6/djX788y5YSEf4iXSuvB0yZ\nS5/ihsyLIlQsmRVS66ueZDC9MQzl03EJC51QIUjJ9pRKvQ9qQZ3OvsciHEvdI6v8\n1r1q5w7k/upNHgrGQnFmRtj3t34rIz0b87Gm3CU6T5ISrXgTAiXAGzVaqPHnOQEw\nlG2YrrW4vZ1FMqbUEon0KoHgI2IONyiZi0yHnnasDyk6i2ifkpSh+21BR9ZBIVK2\nHQIDAQAB\n-----END PUBLIC KEY-----'}}
2022-06-11 16:37:54,663 DEBUG core.py Start auth process for {'account_name': '111', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA5Z10UFQoI5/TSIXmt1LX\nGlEh46bKXtDVmjn3fO5C8RFO1heccW9sbAZRJbXwc1DVcpAX9appy4BLqWMSUYF7\nao2i9QNI4WFe7Mi+qshxoEKOfseyDd79hYZSRlZn6/djX788y5YSEf4iXSuvB0yZ\nS5/ihsyLIlQsmRVS66ueZDC9MQzl03EJC51QIUjJ9pRKvQ9qQZ3OvsciHEvdI6v8\n1r1q5w7k/upNHgrGQnFmRtj3t34rIz0b87Gm3CU6T5ISrXgTAiXAGzVaqPHnOQEw\nlG2YrrW4vZ1FMqbUEon0KoHgI2IONyiZi0yHnnasDyk6i2ifkpSh+21BR9ZBIVK2\nHQIDAQAB\n-----END PUBLIC KEY-----'}
2022-06-11 16:37:54,671 DEBUG core.py Correct username, starting passwd check.
2022-06-11 17:20:46,419 DEBUG decos.py Была вызвана функция main с параметрами (), {}. Вызов из модуля __main__. Вызов из функции main().
2022-06-11 17:23:22,116 DEBUG decos.py Была вызвана функция config_load с параметрами (), {}. Вызов из модуля __main__. Вызов из функции main().
2022-06-11 17:23:22,117 DEBUG decos.py Была вызвана функция arg_parser с параметрами ('', '7777'), {}. Вызов из модуля __main__. Вызов из функции main().
2022-06-11 17:23:22,163 INFO core.py Запущен сервер, порт для подключений: 7777, адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2022-06-11 17:23:29,771 INFO core.py Установлено соедение с ПК ('127.0.0.1', 52612)
2022-06-11 17:23:30,273 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1654957409.7882793, 'user': {'account_name': '111', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA5Z10UFQoI5/TSIXmt1LX\nGlEh46bKXtDVmjn3fO5C8RFO1heccW9sbAZRJbXwc1DVcpAX9appy4BLqWMSUYF7\nao2i9QNI4WFe7Mi+qshxoEKOfseyDd79hYZSRlZn6/djX788y5YSEf4iXSuvB0yZ\nS5/ihsyLIlQsmRVS66ueZDC9MQzl03EJC51QIUjJ9pRKvQ9qQZ3OvsciHEvdI6v8\n1r1q5w7k/upNHgrGQnFmRtj3t34rIz0b87Gm3CU6T5ISrXgTAiXAGzVaqPHnOQEw\nlG2YrrW4vZ1FMqbUEon0KoHgI2IONyiZi0yHnnasDyk6i2ifkpSh+21BR9ZBIVK2\nHQIDAQAB\n-----END PUBLIC KEY-----'}}
2022-06-11 17:23:30,273 DEBUG core.py Start auth process for {'account_name': '111', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA5Z10UFQoI5/TSIXmt1LX\nGlEh46bKXtDVmjn3fO5C8RFO1heccW9sbAZRJbXwc1DVcpAX9appy4BLqWMSUYF7\nao2i9QNI4WFe7Mi+qshxoEKOfseyDd79hYZSRlZn6/djX788y5YSEf4iXSuvB0yZ\nS5/ihsyLIlQsmRVS66ueZDC9MQzl03EJC51QIUjJ9pRKvQ9qQZ3OvsciHEvdI6v8\n1r1q5w7k/upNHgrGQnFmRtj3t34rIz0b87Gm3CU6T5ISrXgTAiXAGzVaqPHnOQEw\nlG2YrrW4vZ1FMqbUEon0KoHgI2IONyiZi0yHnnasDyk6i2ifkpSh+21BR9ZBIVK2\nHQIDAQAB\n-----END PUBLIC KEY-----'}
2022-06-11 17:23:30,281 DEBUG core.py Correct username, starting passwd check.
2022-06-11 17:40:05,039 DEBUG decos.py Была вызвана функция main с параметрами (), {}. Вызов из модуля __main__. Вызов из функции main().
2022-06-11 17:41:34,230 DEBUG decos.py Была вызвана функция config_load с параметрами (), {}. Вызов из модуля __main__. Вызов из функции main().
2022-06-11 17:41:34,236 DEBUG decos.py Была вызвана функция arg_parser с параметрами ('', '7777'), {}. Вызов из модуля __main__. Вызов из функции main().
2022-06-11 17:41:35,432 INFO core.py Запущен сервер, порт для подключений: 7777, адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2022-06-11 17:41:50,387 INFO core.py Установлено соедение с ПК ('127.0.0.1', 53166)
2022-06-11 17:42:11,857 DEBUG decos.py Была вызвана функция get_message с параметрами (<socket.socket fd=25, family=AddressFamily.AF_INET, type=2049, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 53166)>,), {}. Вызов из модуля common.common. Вызов из функции **self.kwargs).
2022-06-11 17:43:08,588 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1654958510.4035816, 'user': {'account_name': '111', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA5Z10UFQoI5/TSIXmt1LX\nGlEh46bKXtDVmjn3fO5C8RFO1heccW9sbAZRJbXwc1DVcpAX9appy4BLqWMSUYF7\nao2i9QNI4WFe7Mi+qshxoEKOfseyDd79hYZSRlZn6/djX788y5YSEf4iXSuvB0yZ\nS5/ihsyLIlQsmRVS66ueZDC9MQzl03EJC51QIUjJ9pRKvQ9qQZ3OvsciHEvdI6v8\n1r1q5w7k/upNHgrGQnFmRtj3t34rIz0b87Gm3CU6T5ISrXgTAiXAGzVaqPHnOQEw\nlG2YrrW4vZ1FMqbUEon0KoHgI2IONyiZi0yHnnasDyk6i2ifkpSh+21BR9ZBIVK2\nHQIDAQAB\n-----END PUBLIC KEY-----'}}
2022-06-11 17:43:15,805 DEBUG core.py Start auth process for {'account_name': '111', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA5Z10UFQoI5/TSIXmt1LX\nGlEh46bKXtDVmjn3fO5C8RFO1heccW9sbAZRJbXwc1DVcpAX9appy4BLqWMSUYF7\nao2i9QNI4WFe7Mi+qshxoEKOfseyDd79hYZSRlZn6/djX788y5YSEf4iXSuvB0yZ\nS5/ihsyLIlQsmRVS66ueZDC9MQzl03EJC51QIUjJ9pRKvQ9qQZ3OvsciHEvdI6v8\n1r1q5w7k/upNHgrGQnFmRtj3t34rIz0b87Gm3CU6T5ISrXgTAiXAGzVaqPHnOQEw\nlG2YrrW4vZ1FMqbUEon0KoHgI2IONyiZi0yHnnasDyk6i2ifkpSh+21BR9ZBIVK2\nHQIDAQAB\n-----END PUBLIC KEY-----'}
2022-06-11 17:44:02,481 DEBUG core.py Correct username, starting passwd check.
2022-06-11 17:49:00,799 DEBUG decos.py Была вызвана функция config_load с параметрами (), {}. Вызов из модуля __main__. Вызов из функции main().
2022-06-11 17:49:00,808 DEBUG decos.py Была вызвана функция arg_parser с параметрами ('', '7777'), {}. Вызов из модуля __main__. Вызов из функции main().
2022-06-11 17:49:01,806 INFO core.py Запущен сервер, порт для подключений: 7777, адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2022-06-11 17:49:22,876 INFO core.py Установлено соедение с ПК ('127.0.0.1', 53354)
2022-06-11 17:49:28,948 DEBUG decos.py Была вызвана функция get_message с параметрами (<socket.socket fd=28, family=AddressFamily.AF_INET, type=2049, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 53354)>,), {}. Вызов из модуля common.common. Вызов из функции **self.kwargs).
2022-06-11 17:49:29,375 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1654958962.8938773, 'user': {'account_name': '111', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtYFaqtdSYzzTGsYuGDmq\nb6Bo/8xdwuPcGsU1fhniJDP7JE1KB1au22Wofce2ywcDB5MzoRex2z0mfGSD7xxF\nehEhzCteU89BQac210edrvvLhxJVbe21cJiEdNQafiKI1+mxysJsQVlodWxDGcXO\nN4vvffHCrBHSQVyXKBwnivMQfFnVpWuqsisYbeknp27znQOmuYjQpkwBw8w6CBWd\npkOaGCZ+qY4RRTzLs58NiiYyEF4I9KSORH9fRSmii1O4GVxTrSWrDhr/+pDINKyQ\nn81TvkhinGkwWPiXdNgqnNeNyKEdFXDkvmkuVKrPS8LbVgNlT3eIXIKgrykAmHFB\nmwIDAQAB\n-----END PUBLIC KEY-----'}}
2022-06-11 17:49:31,676 DEBUG core.py Start auth process for {'account_name': '111', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtYFaqtdSYzzTGsYuGDmq\nb6Bo/8xdwuPcGsU1fhniJDP7JE1KB1au22Wofce2ywcDB5MzoRex2z0mfGSD7xxF\nehEhzCteU89BQac210edrvvLhxJVbe21cJiEdNQafiKI1+mxysJsQVlodWxDGcXO\nN4vvffHCrBHSQVyXKBwnivMQfFnVpWuqsisYbeknp27znQOmuYjQpkwBw8w6CBWd\npkOaGCZ+qY4RRTzLs58NiiYyEF4I9KSORH9fRSmii1O4GVxTrSWrDhr/+pDINKyQ\nn81TvkhinGkwWPiXdNgqnNeNyKEdFXDkvmkuVKrPS8LbVgNlT3eIXIKgrykAmHFB\nmwIDAQAB\n-----END PUBLIC KEY-----'}
2022-06-11 17:49:34,734 DEBUG core.py Correct username, starting passwd check.
2022-06-11 17:53:10,431 DEBUG decos.py Была вызвана функция config_load с параметрами (), {}. Вызов из модуля __main__. Вызов из функции main().
2022-06-11 17:53:10,433 DEBUG decos.py Была вызвана функция arg_parser с параметрами ('', '7777'), {}. Вызов из модуля __main__. Вызов из функции main().
2022-06-11 17:53:10,471 INFO core.py Запущен сервер, порт для подключений: 7777, адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2022-06-11 17:53:22,408 INFO core.py Установлено соедение с ПК ('127.0.0.1', 53442)
2022-06-11 17:53:22,911 DEBUG decos.py Была вызвана функция get_message с параметрами (<socket.socket fd=23, family=AddressFamily.AF_INET, type=2049, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 53442)>,), {}. Вызов из модуля common.common. Вызов из функции self._bootstrap_inner().
2022-06-11 17:53:22,911 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1654959202.4236982, 'user': {'account_name': '111', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtYFaqtdSYzzTGsYuGDmq\nb6Bo/8xdwuPcGsU1fhniJDP7JE1KB1au22Wofce2ywcDB5MzoRex2z0mfGSD7xxF\nehEhzCteU89BQac210edrvvLhxJVbe21cJiEdNQafiKI1+mxysJsQVlodWxDGcXO\nN4vvffHCrBHSQVyXKBwnivMQfFnVpWuqsisYbeknp27znQOmuYjQpkwBw8w6CBWd\npkOaGCZ+qY4RRTzLs58NiiYyEF4I9KSORH9fRSmii1O4GVxTrSWrDhr/+pDINKyQ\nn81TvkhinGkwWPiXdNgqnNeNyKEdFXDkvmkuVKrPS8LbVgNlT3eIXIKgrykAmHFB\nmwIDAQAB\n-----END PUBLIC KEY-----'}}
2022-06-11 17:53:22,911 DEBUG core.py Start auth process for {'account_name': '111', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtYFaqtdSYzzTGsYuGDmq\nb6Bo/8xdwuPcGsU1fhniJDP7JE1KB1au22Wofce2ywcDB5MzoRex2z0mfGSD7xxF\nehEhzCteU89BQac210edrvvLhxJVbe21cJiEdNQafiKI1+mxysJsQVlodWxDGcXO\nN4vvffHCrBHSQVyXKBwnivMQfFnVpWuqsisYbeknp27znQOmuYjQpkwBw8w6CBWd\npkOaGCZ+qY4RRTzLs58NiiYyEF4I9KSORH9fRSmii1O4GVxTrSWrDhr/+pDINKyQ\nn81TvkhinGkwWPiXdNgqnNeNyKEdFXDkvmkuVKrPS8LbVgNlT3eIXIKgrykAmHFB\nmwIDAQAB\n-----END PUBLIC KEY-----'}
2022-06-11 17:53:40,305 DEBUG decos.py Была вызвана функция main с параметрами (), {}. Вызов из модуля __main__. Вызов из функции main().
2022-06-11 17:53:42,894 DEBUG decos.py Была вызвана функция config_load с параметрами (), {}. Вызов из модуля __main__. Вызов из функции main().
2022-06-11 17:53:42,896 DEBUG decos.py Была вызвана функция arg_parser с параметрами ('', '7777'), {}. Вызов из модуля __main__. Вызов из функции main().
2022-06-11 17:53:43,034 INFO core.py Запущен сервер, порт для подключений: 7777, адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2022-06-11 17:53:56,191 INFO core.py Установлено соедение с ПК ('127.0.0.1', 53452)
2022-06-11 17:53:56,694 DEBUG decos.py Была вызвана функция get_message с параметрами (<socket.socket fd=26, family=AddressFamily.AF_INET, type=2049, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 53452)>,), {}. Вызов из модуля common.common. Вызов из функции self._bootstrap_inner().
2022-06-11 17:53:56,695 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1654959236.2067819, 'user': {'account_name': '111', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsTOdpcKoCd5S5ujdjEkr\nZkZc2GRdQHbS7uXel1palOLMNZarK5emLglA0VgNQ+nw6rCRRO5Z2GavA3tBkztJ\n9ao/nZ5zMePBdQD7e6g/OdWYpIkhmTx0yOwMBl9w008F4NS4daP6zyJA4rYmAR58\nBoH6myPspNwciVw+ghjPwSi9dO2gePi5D7UMDcMTbI6OV9ihnkTBDQquskZJu28a\nieSn8yZGc4IkeTtpZVENIFa3+GYn4aTZtv+B1oRqSVroXmCaYcMCe4OkNXjSvwaa\n7asJbqz+j0urgtVYO+ZyYqXVoXD71UbcCNq6aSCq7pfiL0Xjs1cAccWODbDKOFwL\nBwIDAQAB\n-----END PUBLIC KEY-----'}}
2022-06-11 17:53:56,695 DEBUG core.py Start auth process for {'account_name': '111', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsTOdpcKoCd5S5ujdjEkr\nZkZc2GRdQHbS7uXel1palOLMNZarK5emLglA0VgNQ+nw6rCRRO5Z2GavA3tBkztJ\n9ao/nZ5zMePBdQD7e6g/OdWYpIkhmTx0yOwMBl9w008F4NS4daP6zyJA4rYmAR58\nBoH6myPspNwciVw+ghjPwSi9dO2gePi5D7UMDcMTbI6OV9ihnkTBDQquskZJu28a\nieSn8yZGc4IkeTtpZVENIFa3+GYn4aTZtv+B1oRqSVroXmCaYcMCe4OkNXjSvwaa\n7asJbqz+j0urgtVYO+ZyYqXVoXD71UbcCNq6aSCq7pfiL0Xjs1cAccWODbDKOFwL\nBwIDAQAB\n-----END PUBLIC KEY-----'}
2022-06-11 17:53:56,698 DEBUG core.py Correct username, starting passwd check.
2022-06-11 17:53:56,701 DEBUG core.py Auth message = {'response': 511, 'bin': '496db6417c9d636276423f70d59a3fa0ba0a89beec62d7d25d0bd7e35140fb19cfd67afb1d070ec82da9e89e684b7a4b1e0e0b56b693c01f1d9b31689aeb1774'}
2022-06-11 17:53:56,702 DEBUG decos.py Была вызвана функция send_message с параметрами (<socket.socket fd=26, family=AddressFamily.AF_INET, type=2049, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 53452)>, {'response': 511, 'bin': '496db6417c9d636276423f70d59a3fa0ba0a89beec62d7d25d0bd7e35140fb19cfd67afb1d070ec82da9e89e684b7a4b1e0e0b56b693c01f1d9b31689aeb1774'}), {}. Вызов из модуля common.common. Вызов из функции self._bootstrap_inner().
2022-06-11 17:53:56,703 DEBUG decos.py Была вызвана функция get_message с параметрами (<socket.socket fd=26, family=AddressFamily.AF_INET, type=2049, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 53452)>,), {}. Вызов из модуля common.common. Вызов из функции self._bootstrap_inner().
2022-06-11 17:53:56,704 DEBUG decos.py Была вызвана функция send_message с параметрами (<socket.socket fd=26, family=AddressFamily.AF_INET, type=2049, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 53452)>, {'response': 200}), {}. Вызов из модуля common.common. Вызов из функции self._bootstrap_inner().
2022-06-11 17:53:56,704 DEBUG core.py Getting data from client exception.
Traceback (most recent call last):
  File "/home/roma/geekbrains/gb-client-server/gb-client-server-app/server/core.py", line 92, in run
    get_message(client_with_message), client_with_message)
  File "/home/roma/geekbrains/gb-client-server/gb-client-server-app/common/decos.py", line 73, in checker
    return func(*args, **kwargs)
  File "/home/roma/geekbrains/gb-client-server/gb-client-server-app/server/core.py", line 174, in process_client_message
    self.autorize_user(message, client)
  File "/home/roma/geekbrains/gb-client-server/gb-client-server-app/server/core.py", line 341, in autorize_user
    message[USER][PUBLIC_KEY])
TypeError: user_login() takes 4 positional arguments but 5 were given
2022-06-11 17:53:56,705 INFO core.py Клиент ('127.0.0.1', 53452) отключился от сервера.
2022-06-11 18:00:31,869 DEBUG decos.py Была вызвана функция main с параметрами (), {}. Вызов из модуля __main__. Вызов из функции main().
2022-06-11 18:00:43,031 DEBUG decos.py Была вызвана функция config_load с параметрами (), {}. Вызов из модуля __main__. Вызов из функции main().
2022-06-11 18:00:43,033 DEBUG decos.py Была вызвана функция arg_parser с параметрами ('', '7777'), {}. Вызов из модуля __main__. Вызов из функции main().
2022-06-11 18:00:43,072 INFO core.py Запущен сервер, порт для подключений: 7777, адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2022-06-11 18:00:50,351 INFO core.py Установлено соедение с ПК ('127.0.0.1', 53616)
2022-06-11 18:00:50,853 DEBUG decos.py Была вызвана функция get_message с параметрами (<socket.socket fd=23, family=AddressFamily.AF_INET, type=2049, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 53616)>,), {}. Вызов из модуля common.common. Вызов из функции self._bootstrap_inner().
2022-06-11 18:00:50,854 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1654959650.366609, 'user': {'account_name': '111', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsTOdpcKoCd5S5ujdjEkr\nZkZc2GRdQHbS7uXel1palOLMNZarK5emLglA0VgNQ+nw6rCRRO5Z2GavA3tBkztJ\n9ao/nZ5zMePBdQD7e6g/OdWYpIkhmTx0yOwMBl9w008F4NS4daP6zyJA4rYmAR58\nBoH6myPspNwciVw+ghjPwSi9dO2gePi5D7UMDcMTbI6OV9ihnkTBDQquskZJu28a\nieSn8yZGc4IkeTtpZVENIFa3+GYn4aTZtv+B1oRqSVroXmCaYcMCe4OkNXjSvwaa\n7asJbqz+j0urgtVYO+ZyYqXVoXD71UbcCNq6aSCq7pfiL0Xjs1cAccWODbDKOFwL\nBwIDAQAB\n-----END PUBLIC KEY-----'}}
2022-06-11 18:00:50,854 DEBUG core.py Start auth process for {'account_name': '111', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsTOdpcKoCd5S5ujdjEkr\nZkZc2GRdQHbS7uXel1palOLMNZarK5emLglA0VgNQ+nw6rCRRO5Z2GavA3tBkztJ\n9ao/nZ5zMePBdQD7e6g/OdWYpIkhmTx0yOwMBl9w008F4NS4daP6zyJA4rYmAR58\nBoH6myPspNwciVw+ghjPwSi9dO2gePi5D7UMDcMTbI6OV9ihnkTBDQquskZJu28a\nieSn8yZGc4IkeTtpZVENIFa3+GYn4aTZtv+B1oRqSVroXmCaYcMCe4OkNXjSvwaa\n7asJbqz+j0urgtVYO+ZyYqXVoXD71UbcCNq6aSCq7pfiL0Xjs1cAccWODbDKOFwL\nBwIDAQAB\n-----END PUBLIC KEY-----'}
2022-06-11 18:00:50,862 DEBUG core.py Correct username, starting passwd check.
2022-06-11 18:00:50,864 DEBUG core.py Auth message = {'response': 511, 'bin': 'b982ca1cb98012267fc4d9efa9c335622f4578fa7daca2a02b44abebcecf07c4ce291fc79f29d301a238120b0cd87f2aeed0078f8929c6d8c582c5847e2a11b2'}
2022-06-11 18:00:50,865 DEBUG decos.py Была вызвана функция send_message с параметрами (<socket.socket fd=23, family=AddressFamily.AF_INET, type=2049, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 53616)>, {'response': 511, 'bin': 'b982ca1cb98012267fc4d9efa9c335622f4578fa7daca2a02b44abebcecf07c4ce291fc79f29d301a238120b0cd87f2aeed0078f8929c6d8c582c5847e2a11b2'}), {}. Вызов из модуля common.common. Вызов из функции self._bootstrap_inner().
2022-06-11 18:00:50,866 DEBUG decos.py Была вызвана функция get_message с параметрами (<socket.socket fd=23, family=AddressFamily.AF_INET, type=2049, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 53616)>,), {}. Вызов из модуля common.common. Вызов из функции self._bootstrap_inner().
2022-06-11 18:00:50,867 DEBUG decos.py Была вызвана функция send_message с параметрами (<socket.socket fd=23, family=AddressFamily.AF_INET, type=2049, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 53616)>, {'response': 200}), {}. Вызов из модуля common.common. Вызов из функции self._bootstrap_inner().
2022-06-11 18:00:51,387 DEBUG core.py Getting data from client exception.
Traceback (most recent call last):
  File "/home/roma/geekbrains/gb-client-server/gb-client-server-app/server/core.py", line 92, in run
    get_message(client_with_message), client_with_message)
  File "/home/roma/geekbrains/gb-client-server/gb-client-server-app/common/decos.py", line 29, in decorated
    result = func(*args, **kwargs)
  File "/home/roma/geekbrains/gb-client-server/gb-client-server-app/common/common.py", line 20, in get_message
    response = json.loads(json_response)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 342, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 75 (char 74)
2022-06-11 18:00:51,392 INFO core.py Клиент ('127.0.0.1', 53616) отключился от сервера.
2022-06-11 18:02:06,483 DEBUG decos.py Была вызвана функция main с параметрами (), {}. Вызов из модуля __main__. Вызов из функции main().
2022-06-11 18:02:18,797 DEBUG decos.py Была вызвана функция config_load с параметрами (), {}. Вызов из модуля __main__. Вызов из функции main().
2022-06-11 18:02:18,804 DEBUG decos.py Была вызвана функция arg_parser с параметрами ('', '7777'), {}. Вызов из модуля __main__. Вызов из функции main().
2022-06-11 18:02:19,350 INFO core.py Запущен сервер, порт для подключений: 7777, адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2022-06-11 18:02:59,739 DEBUG decos.py Была вызвана функция main с параметрами (), {}. Вызов из модуля __main__. Вызов из функции main().
2022-06-11 18:03:15,319 DEBUG decos.py Была вызвана функция config_load с параметрами (), {}. Вызов из модуля __main__. Вызов из функции main().
2022-06-11 18:03:15,325 DEBUG decos.py Была вызвана функция arg_parser с параметрами ('', '7777'), {}. Вызов из модуля __main__. Вызов из функции main().
2022-06-11 18:03:15,610 INFO core.py Запущен сервер, порт для подключений: 7777, адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2022-06-11 18:03:29,730 INFO core.py Установлено соедение с ПК ('127.0.0.1', 53710)
2022-06-11 18:03:39,654 DEBUG decos.py Была вызвана функция get_message с параметрами (<socket.socket fd=25, family=AddressFamily.AF_INET, type=2049, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 53710)>,), {}. Вызов из модуля common.common. Вызов из функции **self.kwargs).
2022-06-11 18:03:42,245 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1654959809.7472823, 'user': {'account_name': '111', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsTOdpcKoCd5S5ujdjEkr\nZkZc2GRdQHbS7uXel1palOLMNZarK5emLglA0VgNQ+nw6rCRRO5Z2GavA3tBkztJ\n9ao/nZ5zMePBdQD7e6g/OdWYpIkhmTx0yOwMBl9w008F4NS4daP6zyJA4rYmAR58\nBoH6myPspNwciVw+ghjPwSi9dO2gePi5D7UMDcMTbI6OV9ihnkTBDQquskZJu28a\nieSn8yZGc4IkeTtpZVENIFa3+GYn4aTZtv+B1oRqSVroXmCaYcMCe4OkNXjSvwaa\n7asJbqz+j0urgtVYO+ZyYqXVoXD71UbcCNq6aSCq7pfiL0Xjs1cAccWODbDKOFwL\nBwIDAQAB\n-----END PUBLIC KEY-----'}}
2022-06-11 18:03:45,265 DEBUG core.py Start auth process for {'account_name': '111', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsTOdpcKoCd5S5ujdjEkr\nZkZc2GRdQHbS7uXel1palOLMNZarK5emLglA0VgNQ+nw6rCRRO5Z2GavA3tBkztJ\n9ao/nZ5zMePBdQD7e6g/OdWYpIkhmTx0yOwMBl9w008F4NS4daP6zyJA4rYmAR58\nBoH6myPspNwciVw+ghjPwSi9dO2gePi5D7UMDcMTbI6OV9ihnkTBDQquskZJu28a\nieSn8yZGc4IkeTtpZVENIFa3+GYn4aTZtv+B1oRqSVroXmCaYcMCe4OkNXjSvwaa\n7asJbqz+j0urgtVYO+ZyYqXVoXD71UbcCNq6aSCq7pfiL0Xjs1cAccWODbDKOFwL\nBwIDAQAB\n-----END PUBLIC KEY-----'}
2022-06-11 18:03:50,370 DEBUG core.py Correct username, starting passwd check.
2022-06-11 18:03:57,042 DEBUG core.py Auth message = {'response': 511, 'bin': '0c1ea544049d3f3000b44161d7a786c4207e52072bbd6523adff61ad1a077ff909d18088537868d30eda981d88bac01f12e01485124e3adc71bb737959f1e596'}
2022-06-11 18:04:09,601 DEBUG decos.py Была вызвана функция send_message с параметрами (<socket.socket fd=25, family=AddressFamily.AF_INET, type=2049, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 53710)>, {'response': 511, 'bin': '0c1ea544049d3f3000b44161d7a786c4207e52072bbd6523adff61ad1a077ff909d18088537868d30eda981d88bac01f12e01485124e3adc71bb737959f1e596'}), {}. Вызов из модуля common.common. Вызов из функции **self.kwargs).
2022-06-11 18:06:36,805 DEBUG core.py Error in auth, data:
Traceback (most recent call last):
  File "/home/roma/geekbrains/gb-client-server/gb-client-server-app/server/core.py", line 319, in autorize_user
    ans = get_message(sock)
  File "/home/roma/geekbrains/gb-client-server/gb-client-server-app/common/decos.py", line 29, in decorated
    result = func(*args, **kwargs)
  File "/home/roma/geekbrains/gb-client-server/gb-client-server-app/common/common.py", line 18, in get_message
    encoded_response = client.recv(MAX_PACKAGE_LENGTH)
socket.timeout: timed out
2022-06-11 18:07:23,614 DEBUG decos.py Была вызвана функция config_load с параметрами (), {}. Вызов из модуля __main__. Вызов из функции main().
2022-06-11 18:07:23,616 DEBUG decos.py Была вызвана функция arg_parser с параметрами ('', '7777'), {}. Вызов из модуля __main__. Вызов из функции main().
2022-06-11 18:07:23,652 INFO core.py Запущен сервер, порт для подключений: 7777, адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2022-06-11 18:07:36,707 INFO core.py Установлено соедение с ПК ('127.0.0.1', 53832)
2022-06-11 18:07:37,210 DEBUG decos.py Была вызвана функция get_message с параметрами (<socket.socket fd=23, family=AddressFamily.AF_INET, type=2049, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 53832)>,), {}. Вызов из модуля common.common. Вызов из функции self._bootstrap_inner().
2022-06-11 18:07:37,210 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1654960056.7214072, 'user': {'account_name': '111', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsTOdpcKoCd5S5ujdjEkr\nZkZc2GRdQHbS7uXel1palOLMNZarK5emLglA0VgNQ+nw6rCRRO5Z2GavA3tBkztJ\n9ao/nZ5zMePBdQD7e6g/OdWYpIkhmTx0yOwMBl9w008F4NS4daP6zyJA4rYmAR58\nBoH6myPspNwciVw+ghjPwSi9dO2gePi5D7UMDcMTbI6OV9ihnkTBDQquskZJu28a\nieSn8yZGc4IkeTtpZVENIFa3+GYn4aTZtv+B1oRqSVroXmCaYcMCe4OkNXjSvwaa\n7asJbqz+j0urgtVYO+ZyYqXVoXD71UbcCNq6aSCq7pfiL0Xjs1cAccWODbDKOFwL\nBwIDAQAB\n-----END PUBLIC KEY-----'}}
2022-06-11 18:07:37,210 DEBUG core.py Start auth process for {'account_name': '111', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsTOdpcKoCd5S5ujdjEkr\nZkZc2GRdQHbS7uXel1palOLMNZarK5emLglA0VgNQ+nw6rCRRO5Z2GavA3tBkztJ\n9ao/nZ5zMePBdQD7e6g/OdWYpIkhmTx0yOwMBl9w008F4NS4daP6zyJA4rYmAR58\nBoH6myPspNwciVw+ghjPwSi9dO2gePi5D7UMDcMTbI6OV9ihnkTBDQquskZJu28a\nieSn8yZGc4IkeTtpZVENIFa3+GYn4aTZtv+B1oRqSVroXmCaYcMCe4OkNXjSvwaa\n7asJbqz+j0urgtVYO+ZyYqXVoXD71UbcCNq6aSCq7pfiL0Xjs1cAccWODbDKOFwL\nBwIDAQAB\n-----END PUBLIC KEY-----'}
2022-06-11 18:07:37,220 DEBUG core.py Correct username, starting passwd check.
2022-06-11 18:07:37,222 DEBUG core.py Auth message = {'response': 511, 'bin': 'dd2542ad56a72fe5811ecfb3d24f6523065ee0740ed101d401e127e4cd8cbff44c39f8c9db31afd26cb30b43ba521d1a93efbaaafe957605980cdf4fe2b4891f'}
2022-06-11 18:07:37,223 DEBUG decos.py Была вызвана функция send_message с параметрами (<socket.socket fd=23, family=AddressFamily.AF_INET, type=2049, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 53832)>, {'response': 511, 'bin': 'dd2542ad56a72fe5811ecfb3d24f6523065ee0740ed101d401e127e4cd8cbff44c39f8c9db31afd26cb30b43ba521d1a93efbaaafe957605980cdf4fe2b4891f'}), {}. Вызов из модуля common.common. Вызов из функции self._bootstrap_inner().
2022-06-11 18:07:37,223 DEBUG decos.py Была вызвана функция get_message с параметрами (<socket.socket fd=23, family=AddressFamily.AF_INET, type=2049, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 53832)>,), {}. Вызов из модуля common.common. Вызов из функции self._bootstrap_inner().
2022-06-11 18:07:37,224 DEBUG decos.py Была вызвана функция send_message с параметрами (<socket.socket fd=23, family=AddressFamily.AF_INET, type=2049, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 53832)>, {'response': 200}), {}. Вызов из модуля common.common. Вызов из функции self._bootstrap_inner().
2022-06-11 18:07:37,747 DEBUG core.py Getting data from client exception.
Traceback (most recent call last):
  File "/home/roma/geekbrains/gb-client-server/gb-client-server-app/server/core.py", line 92, in run
    get_message(client_with_message), client_with_message)
  File "/home/roma/geekbrains/gb-client-server/gb-client-server-app/common/decos.py", line 29, in decorated
    result = func(*args, **kwargs)
  File "/home/roma/geekbrains/gb-client-server/gb-client-server-app/common/common.py", line 20, in get_message
    response = json.loads(json_response)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 342, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 74 (char 73)
2022-06-11 18:07:37,748 INFO core.py Клиент ('127.0.0.1', 53832) отключился от сервера.
2022-06-11 18:17:20,544 DEBUG decos.py Была вызвана функция config_load с параметрами (), {}. Вызов из модуля __main__. Вызов из функции main().
2022-06-11 18:17:20,548 DEBUG decos.py Была вызвана функция arg_parser с параметрами ('', '7777'), {}. Вызов из модуля __main__. Вызов из функции main().
2022-06-11 18:17:26,440 INFO core.py Запущен сервер, порт для подключений: 7777, адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2022-06-11 18:17:40,341 INFO core.py Установлено соедение с ПК ('127.0.0.1', 54108)
2022-06-11 18:19:13,750 DEBUG decos.py Была вызвана функция get_message с параметрами (<socket.socket fd=25, family=AddressFamily.AF_INET, type=2049, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 54108)>,), {}. Вызов из модуля common.common. Вызов из функции **self.kwargs).
2022-06-11 18:19:16,374 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1654960660.356967, 'user': {'account_name': '111', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsTOdpcKoCd5S5ujdjEkr\nZkZc2GRdQHbS7uXel1palOLMNZarK5emLglA0VgNQ+nw6rCRRO5Z2GavA3tBkztJ\n9ao/nZ5zMePBdQD7e6g/OdWYpIkhmTx0yOwMBl9w008F4NS4daP6zyJA4rYmAR58\nBoH6myPspNwciVw+ghjPwSi9dO2gePi5D7UMDcMTbI6OV9ihnkTBDQquskZJu28a\nieSn8yZGc4IkeTtpZVENIFa3+GYn4aTZtv+B1oRqSVroXmCaYcMCe4OkNXjSvwaa\n7asJbqz+j0urgtVYO+ZyYqXVoXD71UbcCNq6aSCq7pfiL0Xjs1cAccWODbDKOFwL\nBwIDAQAB\n-----END PUBLIC KEY-----'}}
2022-06-11 18:19:16,376 DEBUG core.py Start auth process for {'account_name': '111', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsTOdpcKoCd5S5ujdjEkr\nZkZc2GRdQHbS7uXel1palOLMNZarK5emLglA0VgNQ+nw6rCRRO5Z2GavA3tBkztJ\n9ao/nZ5zMePBdQD7e6g/OdWYpIkhmTx0yOwMBl9w008F4NS4daP6zyJA4rYmAR58\nBoH6myPspNwciVw+ghjPwSi9dO2gePi5D7UMDcMTbI6OV9ihnkTBDQquskZJu28a\nieSn8yZGc4IkeTtpZVENIFa3+GYn4aTZtv+B1oRqSVroXmCaYcMCe4OkNXjSvwaa\n7asJbqz+j0urgtVYO+ZyYqXVoXD71UbcCNq6aSCq7pfiL0Xjs1cAccWODbDKOFwL\nBwIDAQAB\n-----END PUBLIC KEY-----'}
2022-06-11 18:19:16,396 DEBUG core.py Correct username, starting passwd check.
2022-06-11 18:19:16,404 DEBUG core.py Auth message = {'response': 511, 'bin': 'caeb82d539b01ad9a8a530284a683e6c0b9d2fb6a4499d74c34099bc431f1e5ae8ea85d3f8b9b40e44bd61fa70a6bd91057b971dec9deab02e1bb4ad9b0373b7'}
2022-06-11 18:19:16,405 DEBUG decos.py Была вызвана функция send_message с параметрами (<socket.socket fd=25, family=AddressFamily.AF_INET, type=2049, proto=0, laddr=('127.0.0.1', 7777)>, {'response': 511, 'bin': 'caeb82d539b01ad9a8a530284a683e6c0b9d2fb6a4499d74c34099bc431f1e5ae8ea85d3f8b9b40e44bd61fa70a6bd91057b971dec9deab02e1bb4ad9b0373b7'}), {}. Вызов из модуля common.common. Вызов из функции **self.kwargs).
2022-06-11 18:20:15,730 DEBUG core.py Getting data from client exception.
Traceback (most recent call last):
  File "/home/roma/geekbrains/gb-client-server/gb-client-server-app/server/core.py", line 92, in run
    get_message(client_with_message), client_with_message)
  File "/home/roma/geekbrains/gb-client-server/gb-client-server-app/common/decos.py", line 73, in checker
    return func(*args, **kwargs)
  File "/home/roma/geekbrains/gb-client-server/gb-client-server-app/server/core.py", line 174, in process_client_message
    self.autorize_user(message, client)
  File "/home/roma/geekbrains/gb-client-server/gb-client-server-app/server/core.py", line 319, in autorize_user
    ans = get_message(sock)
  File "/home/roma/geekbrains/gb-client-server/gb-client-server-app/common/decos.py", line 29, in decorated
    result = func(*args, **kwargs)
  File "/home/roma/geekbrains/gb-client-server/gb-client-server-app/common/common.py", line 20, in get_message
    response = json.loads(json_response)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
